### ISSUE TITLE
Error: 'Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.0.0.699......'

### ISSUE THREAD

**Issue by SantiSATEC** [IdentityServer/IdentityServer4.Samples#39] opened 2016-06-29 09:08 UTC
In yours 'Mvc and Api' I'm getting this exception on execution time:

Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.0.0.699, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

ON: 
            **app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ScopeName = "api1",
                AutomaticAuthenticate = true
            });**

Any idea??? Thanks!!!!

**Comment by Cuiqs76** [comment] 2016-07-03 02:08
Same Issue in Clients

**Comment by leastprivilege** [comment] 2016-07-03 10:20
this should be fixed per

https://github.com/IdentityServer/IdentityServer4.Samples/issues/38

**Comment by leastprivilege** [comment] 2016-07-04 08:44
I update the package - that should be fixed now.

**Closed** 2016-07-04 08:44 UTC

**Comment by Cuiqs76** [comment] 2016-07-05 03:58
Yes, the problem is fixed. but raise another error. "An error occurred while sending the request."   I set the SampleApi and Console ResourceOwner Flow as setup project.  the line " return client.RequestResourceOwnerPasswordAsync("bob", "bob", "api1 api2", optional).Result;" throw error. can't link the server.

**Comment by leastprivilege** [comment] 2016-07-05 06:48
well - i think that is unrelated. check the exception details.

If you think that is a bug - open a new issue.
